config/routes.rb
PersonalPuzzle::Application.routes.draw do


  get "work_shifts/create"

  get "/log_in" => "sessions#new", :as => "log_in"
  resource :session, :only => %w[create destroy]

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "tasks#index"
  # root :to => "sessions#new"

  resources :users
  resources :clients
  resources :tasks
  resources :completed_shifts
  resources :password_resets
  resources :scheduled_shifts
  resources :schedules

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :date_finished, :deadline_date, :fee, :hourly_rate, :name, :client_id, :archived, :completed_shifts_attributes

  belongs_to :user
  belongs_to :client
  has_many :completed_shifts, :dependent => :destroy
  has_many :scheduled_shifts, :dependent => :destroy

  accepts_nested_attributes_for :completed_shifts

  validates_presence_of :name

  # default_scope :order => 'deadline_date ASC' # Applies to ALL calls to task model, even completed_shifts/scheduled_shifts
  delegate :name, :to => :client, :prefix => true, :allow_nil => true

  def worked_time
    worked_time = 0
    self.completed_shifts.each do |cs|
      worked_time += cs.duration
    end
    worked_time
  end

  def work_time
    work_time = (self.fee.to_f / self.hourly_rate.to_f) * 3600
  end

  def worked_percentage
    worked_percentage = ((self.worked_time / self.work_time) * 100).round
  end

  def hourly_pay
    if worked_time > 0
      self.fee / worked_time.to_f
    else
      self.hourly_rate # Warning! This is a fallback if a task is marked as completed without any completed shifts.
    end
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks.order('deadline_date ASC')
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.new(params[:task])

    if @task.save
      redirect_to root_url, :notice => "Jobbet \"" + @task.name + "\" sparat!"
    else
      render "new"
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to tasks_url, :notice => "Jobbet \"" + @task.name + "\" uppdaterat!"
    else
      render "edit"
    end
  end

  def destroy
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :name, :label => "Namn" %>
  <%= f.association :client, :prompt => "Välj uppdragsgivare", :label => "Uppdragsgivare" %>
  <%= link_to "Skapa ny uppdragsgivare", new_client_path %>

  <%= f.input :fee, :label => "Arvode" %>

  <%= f.input :deadline_date, :label => "Deadline-datum" %>
  <%= f.input :hourly_rate, :label => "Timtaxa" %>
  <%= f.submit 'Spara jobb' %>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Redigera <%= @task.name %></h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    function timer(box, timer_status) {
      if($(box).find('.counter').hasClass('hasCountdown')) {
        if (timer_status == "running") {
          $(box).find('.counter').countdown('pause')
        } else if (timer_status == "paused") {
          $(box).find('.counter').countdown('resume')
        }
      } else {
        var start_time = new Date();
        $(box).find('.counter').countdown({since: start_time, compact: true, format: 'HMS' });
        $(box).find('.shift_duration').html('');
      }
    };

    $(document).ready(function() {
      $('.timer-box').each(function(i, box){
        var timer_status = "unstarted";

        $(box).find('.btn.icon-play').click(function(){
          if (timer_status == "running"){
            $(box).find('.progress').removeClass('progress-striped active');
            timer(box, timer_status);
            $(this).toggleClass("icon-pause");
            timer_status = "paused";
          } else {
            $(box).find('.progress').addClass('progress-striped active');
            timer(box, timer_status);
            $(this).toggleClass("icon-pause");
            timer_status = "running";
          }
        });

        $(box).find('.btn.icon-ok').click(function(){
          var shift_duration_array = $(box).find('.counter').find('.countdown_row').html().split(":");
          var counter_duraton = $(box).find('.counter').countdown('getTimes')
          var shift_duration = (shift_duration_array[0] * 3600) + (shift_duration_array[1] * 60) + (shift_duration_array[2]) * 1;

          $(box).find('.counter').countdown('destroy');
          $(box).find('.shift_duration').html('Du jobbade i ' + shift_duration + ' sekunder');
          var task_id = $(box).find('.id.hidden').text();

          $.ajax( {
            url:        "<%= completed_shifts_path %>",
            type:       "POST",
            dataType:   "json",
            data:       { task_id:task_id, duration:shift_duration },
            success:    function(data, textStatus, xhr)   {
                          // alert("Arbetspasset sparat!")
                          $(box).find('.progress').find('.bar').css('width', data.worked_percentage + '%');
                          $(box).find('.worked-time').html('<p>Du har jobbat ' + data.worked_time + ' sekunder av totalt ' + data.work_time + '</p>');
                        },
            error:      function(request, status, error) {
                  },
          });
        });
      });
    });

  </script>
<% end %>

<h1>Aktiva jobb</h1>
<ul class="unstyled">
  <% no_active_tasks = true %>
  <% @tasks.each do |t| %>
    <% if t.date_finished == nil and !t.archived %>
      <li class="well timer-box">
        <div class="task_info">
          <%= link_to t.name, task_path(t) %> åt <%= link_to t.client_name, client_path(t) %>, deadline: <%= t.deadline_date.to_s(:short) %>
          <div class="id hidden"> <%= t.id %> </div>
        </div>
        <div class="pull-left task-control">
          <button class="btn icon-play">
          </button>
          <button class="btn icon-ok btn-success">
          </button>
        </div>
        <div class="progress">

          <div class="bar" style="width: <%= number_to_percentage((t.worked_time / t.work_time) * 100, :precision => 0) %>;">
          </div>
        </div>
        <div class="pull-right">
            <%= button_to "Klar?", task_path(t, :task => { :date_finished => DateTime.now }), :method => :put, :class => %w[btn btn-success] %>
        </div>
        <div class="pull-right">
            <%= button_to "Arkivera", task_path(t, :task => { :archived => true }), :method => :put, :class => %w[btn] %>
        </div>
        <div class='worked-time'>
          <p>Du har jobbat <%= t.worked_time %> sekunder av totalt <%= t.work_time.round %></p>
        </div>
        <div class="counter">
        </div>
        <div class="shift_duration">
        </div>
      </li>
      <% no_active_tasks = false %>
    <% end %>
  <% end %>
  <% if no_active_tasks %>
    <ul class="unstyled">
      <div class="well">
        <i>Inga aktiva jobb!</i>
      </div>
    </ul>
  <% end %>
</ul>

<h2>Klara jobb</h2>
<div class="well">
  <ul class="unstyled">
    <% no_finished_tasks = true %>
    <% @tasks.each do |t| %>
      <% if t.date_finished %>
        <li>
          <p><%= link_to t.name, task_path(t) %></p>
          <p>Datum klart: <%= t.date_finished.to_s(:short) %></p>
        </li>
        <% no_finished_tasks = false %>
      <% end %>
    <% end %>
    <% if no_finished_tasks%>
      <i>Inga klara jobb!</i>
    <% end %>
  </ul>
</div>

<h2>Arkiverade jobb</h2>
<div class="well">
  <ul class="unstyled">
    <% no_archived_tasks = true %>
    <% @tasks.each do |t| %>
      <% if t.archived %>
        <li>
          <p><%= link_to t.name, task_path(t) %></p>
        </li>
        <% no_archived_tasks = false %>
      <% end %>
    <% end %>
    <% if no_archived_tasks%>
      <i>Inga arkiverade jobb!</i>
    <% end %>
  </ul>
</div>

<%= link_to "Skapa nytt jobb", new_task_path %>

app/views/tasks/new.html.erb
<h1>Skapa nytt jobb</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<% t = @task %>
<h1><%= t.name %></h1>
<h2>Uppdragsgivare: <%= t.client_name %></h2>
<h2>Timtaxa: <%= t.hourly_rate %> kr</h2>
<h2>Arvode: <%= t.fee %> kr</h2>
<h2>Deadline: <%= t.deadline_date.to_s(:short) %></h2>
<div class="well well-small">

  <% if t.date_finished != nil %>
    <h2>Status: Klart!</h2>
    <%= button_to "Återaktivera", task_path(t, :task => { :date_finished => :null }), :method => :put, :class => %w[btn btn-primary] %>
  <% elsif t.archived %>
    <h2>Status: Arkiverat!</h2>
    <%= button_to "Återaktivera", task_path(t, :task => { :archived => false }), :method => :put, :class => %w[btn btn-primary] %>
  <% else %>
    <h2>Status: Aktivt!</h2>
    <%= button_to "Arkivera?", task_path(t, :task => { :archived => true }), :method => :put, :class => %w[btn btn-primary] %>
  <% end %>
</div>
<h2>Arbetade pass:</h2>
<div class="well">
  <ul class="unstyled zebra-striped">
    <% t.completed_shifts.each do |cs| %>
      <li>
        <%= link_to "", completed_shift_path(cs), :method => :delete, :confirm => "Är du säker på att du vill ta bort arbetspasset?", :class => %w[btn btn-danger icon-remove pull-right] %>
        <p>Starttid: <%= cs.start_date.to_s(:short) %></p>
        <p>Längd: <%= cs.duration %> sekunder </p>
      </li>
    <% end %>
  </ul>
  <% if t.completed_shifts.size == 0 %>
    <p>Inga arbetade pass för "<%= t.name %>" ännu!</p>
  <% end %>
  <%= link_to "Lägg till pass manuellt", new_completed_shift_path(:t => t) %>

</div>

<%= link_to "Redigera jobbet", edit_task_path(t) %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>