config/routes.rb
PersonalPuzzle::Application.routes.draw do


  get "work_shifts/create"

  get "/log_in" => "sessions#new", :as => "log_in"
  resource :session, :only => %w[create destroy]

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "tasks#index"
  # root :to => "sessions#new"

  resources :users
  resources :clients
  resources :tasks
  resources :completed_shifts
  resources :password_resets
  resources :scheduled_shifts
  resources :schedules

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :standard_rate, :tasks_attributes
  has_many :tasks
  belongs_to :user

  accepts_nested_attributes_for :tasks

  validates_presence_of :name
  validates_numericality_of :standard_rate, :greater_than_or_equal_to => 0, :allow_nil => true


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = current_user.clients.all
  end

  def new
    @client = current_user.clients.new
  end

  def create
    @client = current_user.clients.new(params[:client])

    if @client.save
      redirect_to clients_url, :notice => "Uppdragsgivaren \"" + @client.name + "\" sparad!"
    else
      render "new"
    end
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(params[:client])
      redirect_to root_url, :notice => "Uppdragsgivaren \"" + @client.name + "\" uppdaterad!"
    else
      render "edit"
    end
  end

  def destroy
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %>
  <%= f.input :name, :label => "Namn" %>
  <%= f.input :standard_rate, :label => "Standard timlön" %>
  <%= f.submit 'Spara uppdragsgivare', :class => %w[btn btn-success] %>
<% end %>

app/views/clients/edit.html.erb
<h1>Redigera kund</h1>

<%= render 'form' %>

<%= button_to 'Ta bort uppdragsgivare', client_path(@client), :method => :delete, :confirm => 'Är du säker?', :class => %w[btn btn-danger] %>

app/views/clients/index.html.erb
<h1>Uppdragsgivare</h1>
<ul>
  <% @clients.each do |c| %>
    <li><%= link_to c.name, client_path(c) %></li>
  <% end %>
</ul>

<% if current_user.has_any_completed_tasks? %>
  <div id="client-statistics">
    <h2>Mest lönsamma kund (högst arvode per timme):</h2>
    <div class="well">
      <ul>
        <% current_user.most_profitable_client.each do |prof| %>
          <li><%= prof[0] %>, med <%= prof[1].round%> kronor i timmen</li>
        <% end %>
      </ul>
    </div>
    <h2>Kund du jobbat mest för:</h2>
    <div class="well">
      <ul>
        <% current_user.most_worked_for_client.each do |prof| %>
          <li><%= prof[0] %>: <%= prof[1].round%> timmar</li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <p><i>När du slutfört ditt första jobb kan du se statistik om uppdragsgivare här!</i></p>
<% end %>

<%= link_to "Lägg till uppdragsgivare", new_client_path %>

app/views/clients/new.html.erb
<h1>Skapa ny kund</h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<% c = @client %>
<h1><%= c.name %></h1>
<h2>Standardarvode:</h2>
<div class="well">
  <%= c.standard_rate %> kronor i timmen
</div>
<h2>Jobb utförda för <%= c.name%>:</h2>
<div class="well">
  <%= current_user.number_of_tasks_for(c) %>
</div>
<%= link_to ("Redigera " + c.name), edit_client_path(c) %>