config/routes.rb
PersonalPuzzle::Application.routes.draw do


  get "work_shifts/create"

  get "/log_in" => "sessions#new", :as => "log_in"
  resource :session, :only => %w[create destroy]

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "tasks#index"
  # root :to => "sessions#new"

  resources :users
  resources :clients
  resources :tasks
  resources :completed_shifts
  resources :password_resets
  resources :scheduled_shifts
  resources :schedules

end

app/models/scheduled_shift.rb
class ScheduledShift < ActiveRecord::Base
  attr_accessible :duration, :start_date, :task_id

  belongs_to :task

  delegate :name, :to => :task, :prefix => true, :allow_nil => true

end

app/controllers/scheduled_shifts_controller.rb
class ScheduledShiftsController < ApplicationController
  def index
    @scheduled_shifts = current_user.scheduled_shifts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scheduled_shifts }
    end
  end

  def show
    @scheduled_shift = ScheduledShift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scheduled_shift }
    end
  end

  def new
    @scheduled_shift = ScheduledShift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scheduled_shift }
    end
  end

  def edit
    @scheduled_shift = ScheduledShift.find(params[:id])
  end

  def create
    @scheduled_shift = ScheduledShift.new(params[:scheduled_shift])

    respond_to do |format|
      if @scheduled_shift.save
        format.html { redirect_to @scheduled_shift, notice: 'Scheduled shift was successfully created.' }
        format.json { render json: @scheduled_shift, status: :created, location: @scheduled_shift }
      else
        format.html { render action: "new" }
        format.json { render json: @scheduled_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @scheduled_shift = ScheduledShift.find(params[:id])

    respond_to do |format|
      if @scheduled_shift.update_attributes(params[:scheduled_shift])
        format.html { redirect_to @scheduled_shift, notice: 'Scheduled shift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scheduled_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @scheduled_shift = ScheduledShift.find(params[:id])
    @scheduled_shift.destroy

    respond_to do |format|
      format.html { redirect_to scheduled_shifts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scheduled_shifts_helper.rb
module ScheduledShiftsHelper
end

app/views/scheduled_shifts/_form.html.erb
<%= simple_form_for(@scheduled_shift) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :task_id %>
    <%= f.input :start_date %>
    <%= f.input :duration %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scheduled_shifts/edit.html.erb
<h1>Editing scheduled_shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduled_shift %> |
<%= link_to 'Back', scheduled_shifts_path %>

app/views/scheduled_shifts/new.html.erb
<h1>New scheduled_shift</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduled_shifts_path %>

app/views/scheduled_shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @scheduled_shift.task_id %>
</p>

<p>
  <b>Start date:</b>
  <%= @scheduled_shift.start_date %>
</p>

<p>
  <b>Duration:</b>
  <%= @scheduled_shift.duration %>
</p>


<%= link_to 'Edit', edit_scheduled_shift_path(@scheduled_shift) %> |
<%= link_to 'Back', scheduled_shifts_path %>