config/routes.rb
PersonalPuzzle::Application.routes.draw do


  get "work_shifts/create"

  get "/log_in" => "sessions#new", :as => "log_in"
  resource :session, :only => %w[create destroy]

  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "tasks#index"
  # root :to => "sessions#new"

  resources :users
  resources :clients
  resources :tasks
  resources :completed_shifts
  resources :password_resets
  resources :scheduled_shifts
  resources :schedules

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PersonalPuzzle" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= content_for?(:head) ? yield(:head) : nil %>

  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">PP</a>
          <div class="btn-group pull-right">
            <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
              <i class="icon-user"></i>
              <% if current_user %>
                <%= current_user.email %>
              <% else %>
                Logga in
              <% end %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <% if current_user %>
                <li><%= link_to current_user.email, user_path(current_user.id) %></li>
                <li class="divider"></li>
                <li><%= button_to "Logga ut", session_path, :id => "log_out", :method => :delete, :class => :btn %></li>
              <% else %>
                <li><%= link_to "Registrera dig", sign_up_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logga in", log_in_path %></li>
              <% end %>
            </ul>
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <% if current_user %>
                <li><%= link_to "Jobb", tasks_path %></li>
                <li><%= link_to "Uppdragsgivare", clients_path  %></li>
                <li><%= link_to "Planering", schedules_path %></li>
              <% else %>
                <li><%= link_to "Perzonal Pazzle", "/path3"  %></li>
              <% end %>
            </ul>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <% if flash[:alert] %>
      <%= content_tag :div, :id => "flash_alert", :class =>"alert alert-error" do %>
        <button class="close" data-dismiss="alert">×</button>
          <%= flash[:alert] %>
      <% end %>
    <% end %>

    <% if flash[:notice] %>
      <%= content_tag :div, :id => "flash_notice", :class =>"alert alert-success" do %>
        <button class="close" data-dismiss="alert">×</button>
          <%= flash[:notice] %>
      <% end %>
    <% end %>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span5">
              <%= yield %>
            </div>
        <!--<div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div>/.well -->
            <!--</div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; T3KNiK 2012</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>